services:
  - type: web
    name: resetsupplymx
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: PUBLIC_URL
        sync: false
